stages:
  - build
  - test
  - deploy

build-services:
  stage: build
  script:
    - docker-compose build

test-services:
  stage: test
  script:
    - docker-compose up -d
    - sleep 30
    - cd ./tests && npm install && npm test
    - cd .. && docker-compose down

deploy-services:
  stage: deploy
  script:
    - docker-compose up -d
  only:
    - project
