services:
  service1:
    build: ./service1
    image: service1_image
    depends_on:
      - service2
    environment:
      - PORT=8199
    deploy:
      replicas: 3
    volumes:
      - ./shared-entrypoint.sh:/usr/local/bin/shared-entrypoint.sh
      - /shared:/shared
    networks:
      - loadbalancing

  service2:
    build: ./service2
    image: service2_image
    volumes:
      - ./shared-entrypoint.sh:/usr/local/bin/shared-entrypoint.sh
      - /shared:/shared
    networks:
      - loadbalancing

  api-gateway:
    build: ./api-gateway
    image: api_gateway_image
    environment:
      - PORT=8198
    volumes:
      - ./shared-entrypoint.sh:/usr/local/bin/shared-entrypoint.sh
      - /shared:/shared
    networks:
      - loadbalancing

  nginx:
    build: ./nginx
    image: nginx_image
    ports:
      - "8197:8197"
    depends_on:
      - service1
      - api-gateway
    volumes:
      - ./shared-entrypoint.sh:/usr/local/bin/shared-entrypoint.sh
      - /shared:/shared
    networks:
      - loadbalancing

networks:
  loadbalancing:
